# Sử dụng NodeJS base image nhẹ
FROM node:18.12.1-bullseye-slim

# Thư mục làm việc trong container
WORKDIR /usr/src/app

# Copy package.json và lockfile (nếu có, ví dụ yarn.lock hoặc package-lock.json)
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Copy toàn bộ mã nguồn vào container
COPY . .

# Expose cổng server (đảm bảo server.js lắng nghe đúng port này)
EXPOSE 3060

# Command khởi động backend
CMD ["npm", "start"]
