apiVersion: v1
kind: Secret
metadata:
  name: giftapp-secret
type: Opaque
stringData:
  JWT_SECRET: "secretkey123"
  JWT_EXPIRES_IN: "1h"
  LOG_FILE_PATH: "logs/combined.log"
  LOG_ERROR_FILE_PATH: "logs/error.log"
  LOG_DEBUG_FILE_PATH: "logs/debug.log"
